### ISSUE TITLE
Custome Model Is giving null exception

### ISSUE THREAD

**Issue by aliBUT** [MatthewHallberg/TensorFlowUnity-ImageClassification#2]
Hi Matthew,
I am been researching your code and I trained my own model to detect few things at home. The model I trained is working fine in python. but when I freeze it and use it in unity by changing its extension to bytes it gives me null exception at 
`runner.AddInput (graph [INPUT_TENSOR] [0], tensor).Fetch (graph [OUTPUT_TENSOR] [0]);`

I have tensorflow 1.71 installed on my training pc. which is the same as unity tensorflow version.
I also made sure to change label map file with my own labels . is it possible that the way i am freezing is wrong? i am using googles object recognition export_inference_graph.py python file

**Comment by ghost** [comment]
Did you mage to fix this issue? Im also getting the same one

**Comment by aliBUT** [comment]
nope i didn't
