### ISSUE TITLE
TensorflowSharp problem

### ISSUE THREAD

**Issue by Atik-Ahamed** [MatthewHallberg/TensorFlowUnity-ImageClassification#3]
"Assets/Scripts/Classification.cs(39,9): error CS0103: The name `TensorFlowSharp' does not exist in the current context"

I'm getting the above error.

**Comment by farzad-salimijazi** [comment]
I have the same problem

**Comment by Atik-Ahamed** [comment]
#if UNITY_ANDROID && !UNITY_EDITOR
        TensorFlowSharp.Android.NativeBinding.Init();
#endif
i solved this by editing to above
notice the change _"&&!UNITY_EDITOR"_
